[package]
name = "ratatui_example"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
ratatui = "0.28.1"

[dev-dependencies]
strum = "0.26"
rand = "0.8"
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3"
