[package]
name = "demo2"
version = "0.1.0"
edition = "2021"

[lib]
name = "demo2"
path = "src/lib.rs"

[[bin]]
name = "demo2"
path = "src/main.rs"

[dependencies]
anyhow = "1"
rand = "0.8"
ratatui = "0.29"
tokio = { version = "1", features = ["full"] }
crossterm = "0.28"
